# Generated by Django 3.2.8 on 2022-03-30 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
        ('delivery_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date_applied', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.reader')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('head', models.CharField(max_length=20, null=True)),
                ('body', models.TextField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.reader')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.reader')),
            ],
        ),
    ]
