# Generated by Django 3.2.8 on 2022-03-30 12:48

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_management', '0002_complaints_notification_request'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='borrowel',
            index=models.Index(django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('end_quality'), '-', django.db.models.expressions.F('start_quality')), name='quality_reduction'),
        ),
        migrations.AddIndex(
            model_name='borrowel',
            index=models.Index(fields=['-deadline', 'start_date'], name='delivery_ma_deadlin_5b8d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowel',
            index=models.Index(fields=['book'], name='delivery_ma_book_id_c3712a_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowel',
            index=models.Index(fields=['reader'], name='delivery_ma_reader__5c83e7_idx'),
        ),
    ]
