# Generated by Django 3.2.8 on 2022-03-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0002_wishlist'),
        ('user_management', '0001_initial'),
        ('delivery_management', '0003_auto_20220330_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.deliveryman'),
        ),
        migrations.AlterUniqueTogether(
            name='borrowel',
            unique_together={('book', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('user', 'Date_applied')},
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['Date_applied'], name='delivery_ma_Date_ap_b26947_idx'),
        ),
    ]
