# Generated by Django 3.2.8 on 2022-03-30 16:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0003_auto_20220330_1827'),
        ('delivery_management', '0006_auto_20220330_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_management.book'),
        ),
        migrations.AlterField(
            model_name='borrowel',
            name='deadline',
            field=models.DateField(default=datetime.date(2022, 4, 6)),
        ),
    ]
