# Generated by Django 3.2.8 on 2022-03-31 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_management', '0009_auto_20220330_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowel',
            name='deadline',
            field=models.DateField(default=datetime.date(2022, 4, 7)),
        ),
    ]
