# Generated by Django 3.2.8 on 2022-04-13 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_management', '0010_alter_borrowel_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowel',
            name='due_extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrowel',
            name='deadline',
            field=models.DateField(default=datetime.date(2022, 4, 20)),
        ),
    ]
