# Generated by Django 3.2.8 on 2022-04-26 17:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_deliveryman_cash_balance'),
        ('delivery_management', '0011_auto_20220413_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowel',
            name='delivery_man',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.deliveryman'),
        ),
        migrations.AlterField(
            model_name='borrowel',
            name='deadline',
            field=models.DateField(default=datetime.date(2022, 5, 3)),
        ),
    ]
