# Generated by Django 3.2.8 on 2022-04-26 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_deliveryman_cash_balance'),
        ('delivery_management', '0012_auto_20220426_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowel',
            name='delivery_man',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.deliveryman'),
        ),
    ]
