# Generated by Django 3.2.8 on 2022-03-30 03:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('language', models.CharField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Sinhala', 'Sinhala')], default='Tamil', max_length=10)),
                ('quality', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_management.library')),
            ],
        ),
    ]
