# Generated by Django 3.2.8 on 2022-03-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
        ('book_management', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('book', 'reader')},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['name'], name='name_index'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='author_index'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['language'], name='language_index'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['book'], name='book_index'),
        ),
    ]
