# Generated by Django 3.2.8 on 2022-03-29 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.reader')),
            ],
        ),
    ]
