# Generated by Django 3.2.8 on 2022-03-29 06:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_librarian'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_balance', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('reader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.reader')),
            ],
        ),
    ]
