# Generated by Django 3.2.8 on 2022-03-30 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryman',
            name='id',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='id',
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='reader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_management.reader'),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='reader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_management.reader'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
