# Generated by Django 3.2.8 on 2022-03-29 06:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanagement', '0003_deliveryman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=1000)),
                ('subscription_fee', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('librarian', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='usermanagement.librarian')),
            ],
        ),
    ]
