# Generated by Django 3.2.8 on 2022-03-30 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0003_auto_20220330_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='fine',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
