# Generated by Django 3.2.8 on 2022-03-31 03:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_deliveryman_cash_balance'),
        ('library_management', '0004_membership_fine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('deliveryman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.deliveryman')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_management.library')),
            ],
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['library'], name='library_payment_index'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['deliveryman'], name='deliveryman_payment_index'),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('library', 'deliveryman')},
        ),
    ]
